### ISSUE TITLE
Attach APK to release?

### ISSUE THREAD

**Issue by IzzySoft** [peterhearty/WipeFiles#1]
Hi Peter,

would you consider attaching the `.apk` file with your `releases/` here on Github – so people running Google-free devices w/o Playstore access can grab your app? I'd then even offer to [add it here](https://android.izzysoft.de/repo), so your users can get updates automatically using the F-Droid client.

Thanks in advance!

**Comment by peterhearty** [comment]
I've attached the apk as a zip to the latest release.

**Comment by IzzySoft** [comment]
Thanks, Peter! For future updates, would you mind attaching the plain `.apk` (instead of zipping it)? Makes it easier for my auto-updater :)

**Comment by peterhearty** [comment]
I tried attaching a plain apk to the release but it wouldn't let me. How do you do it?

**Comment by IzzySoft** [comment]
That's strange. I'm not an Android dev, so I never had to attach an `.apk` – but I see so many projects having it attached – and other than with your `/releases` page it doesn't show as a "link inside the text", but next to the `.zip` and `.tar.gz` in the "Download List" section.

Note when editing the release, there are 2 sections to attach files. You obviously used the first ("Attach **_files_** by dragging & dropping or selecting them"). Below that is a separate section "Attach **_binaries_** by dropping them here or selecting them." (emphasis mine in both cases). You obviously used the former (as the file appears in your release notes), but should use the latter I'd say. Not tried myself, though ;)

**Comment by peterhearty** [comment]
Thanks, that worked. I'll try to remember that for next time.

**Comment by IzzySoft** [comment]
Cool – thanks to you again! My updater will no fetch it whenever you make a new release, so it should be updated in the repo within 24h then.
